---
kind: pipeline
name: default
  
clone:
  disable: true
  
steps:  

- name: clone-and-verify
  image: quay.io/natlibfi/drone-verify-git
  settings:
  signing_keys:
    from_secret: signing_keys

- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags

- name: docker 
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/melinda-record-import-harvester-publication-archives
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: secret
name: docker_username
data: cD5+M0ewgctfCeg+ZZqpzjT75SNtoKOCCGtxaa2LKLOQ9HnlQmX/GifRakKxmJfMGCEx1M/afZlOCQ==
---
kind: secret
name: docker_password
data: ihT0ZLQ0oz9cJUqc/ZuueXnW8I3A9sQSF7MqUlQkx3lD2iB62HCiy86dt7kofoJ9fM04VFe3eeQvXYlBvViwvY4fViKmhwtmKsEZd7RYTFRWPVK1VjQuI1xXrZ0=
---
kind: secret
name: signing_keys
data: OlLotdIooTxxEG7VlkQ6LIQrgYkKfnjZGWjGVA+9YuVzx9DMQU492OZfqJHPB/o5tE6PULAMI8MtS9Cr2GVszemKXWjA3wpR/fxOiAzkLqKYY9lIKw2Ow/DKUMGMeK2/2ELiaHHUukgKA1AgdVwBvyM/XxUqQeMSidyFfMOK3YEoLZ260PCEifQDwBWBjeAgGbxdUvyJfGjARWpGyt79631byjfCbxEvy+lvDTVwushVYClJjs19IbbKEoR/jkC5AkxzDySKydbshbtjA0tfP0NMt9uKNmjJgVuiFPUfJGUlGCp8sgQXrU7zznDQ+fWz9VTHG8aCVS7WZ8YQe4u44OriW+qujwB8Zl5wur/QZWOxuFzxoC8ot/L4A9rn2nm2uuI0YySDm68ZCwZn6yVX7ayzfaEgEzDeA9IiHAoscQe5OiL4NcRDl7AQjYhjqmY8dZHo3I2cHoq4zwz4NUfPM+FVsCilhcRRRMJoL1TLxPjryYY/ztAAKjmpxSyVODCo5qOIJrhH4FIVwpta4EHm/UWstj4nngjXkJip/lrKyNP7qTQT9MKCShCHE3J3UA9CtIiNcsXKEXeMQKCRiZygumhIxu1C8JkwuDwwWLUDBob6qScZvivDDBuqkOTr7lWWib1HG3Gj9cYo+GuS0GCquhkC3hjy32j02Yk8rOfnUULxAlN9CWL/dSsLK1K0ejWxrnPcxZDXhNzSIvBfWLa26hDFpWe+llrH4xqlSIUfLhOzy/QhwHnGfYbQSijVNKMokT84c9WCNyh2XbDfGCa5IDpGW9BokcrGyZ+cVMUs6F3/obW+CM+bBDPzuBwmhkDGpQcnVRTa2vdVT+EpnspNwjbhYNNZIaUE+Qtn/p5N0VQ9wNk4WffB3N40wI9+pJ73my+Gu1rQlF2dJUP41mDjKRDcHHKxzFbJ5SoVY+5nKKmvJVJGYs0HWs2dNjTy93a/pFniqsSAkFh2awpX7ED0hIGXejc/rkAxqBkIQK/vvbOBU0GfQ7z8Ne1RePfCHozQu9P4LihAVDgoTY89OzJRMbDaLQbZTJgZyfi9LRapixHCVrGqD1+Xh3PwSf3hfHaZHOxUKRsJ63VUufs6FCf9Uy2PkQL9lL5jXOiOzpH9edC3NlAHKuiMYx7QB7b/rbMQGN78t20I3b6jSvOkPsQVemJlX+D61plB2uM7fxeOXETXO2AHXeFl57rWXyFnvcxYwVaQJoEHeBgGWsCpX4bu0VaycgPGoa3Z0wNtA9PG9qupj2GGN3nnWPbau8QG9GxvfTMovgvzCJPJysv0Gw41ow7R6cTx3ptnWdkbSvYk4DGCvoghow3LIIRY7NJ5kVT3dtV3vcbETVWYGUpBOLpgbAx+yCOkHqX2JEE4kObJ8LZHFCsrTMilB2t3Em6iERrIesjuRH6/+ld0F93GBSAuIwb7DkbdMOfoUXdxXscldpaZFSZDsbqysxh+kMMqjSTaSBtpR0flwDO42bfxhK3qOKPW3LOyIDSNM2/c1NHLinUk3cU4rTuZXxwLShSvdkJ7B8oVMzfnDrFsANR1GWllCX87Y1D9DmZYbVTTOcZDc3zET5TWn1+Af7SQ0mZHylPFZr704Sazac59x7dZaOn4gce+lYHlSearCijwObPSJmNUZYq88joSudSSAPzB3vwn3BX+M68toRo910hoO6ix+Y5LNIwSYhzQ988e7sCXEny6bZ/9eId+BtaAaF2Tf5HB8c7tYzZomZeyuVjmc0AAfZoLzLle0lYn6A0CT//tBVti1hRV5yUOtUDtduD8Bh6TVzoXpK8W4FAWafm8RLt5O8z1s4AymUaW2RY92zvCVGN2oPNveuX2hrhx82ViWQml6iauEBThFy3OQRaQQi6dtxevQAmCzJR1nGL0pEHPEIbYbXHSUko4AXAcXbWj4+Oq2kr57jccbSIMnWGhb9wR7Ewp41ZjmNznh/qDX7vjY95h5lFej3Fg6AJAF8gIc1+N40aVD4t+CwHg7KMk1pIMvmXWjIgGCQK2575sYFkxW4OT3mSulfmRIwHcFyjf7ADLe4w2gyTdUt2IC87P1EcU9WzIRVTnbsv1Y4ru705l5mqw7rysnu010JCMw5ujfE26sfGh66W/iKJb4cco9sx4dNIbsH5H63CaIc9vYO4vnB2kfyeX+pXnhoO7yqS97h1m7xkkNiTg9jUwXr3+JpcsuZk4KM6ZYhXGp4cF/aO3I1ALEM4frLgz9ij/rHEbfsbi/77hj3QT

---
kind: signature
hmac: 3dd8a986ced8ef589a8cbe4435d646adb51095aeca4ee9e6e86cdf4716248256

...
